"""add cart category specs and multi price

Revision ID: 268848281cbf
Revises: aa523d95c95e
Create Date: 2026-06-23 02:52:53.694592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '268848281cbf'
down_revision: Union[str, None] = 'aa523d95c95e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    cart_category = sa.Enum('hand_truck', 'flat_cart', 'hand_dolly', 'outdoor_wagon', 'other', name='cart_category')
    cart_category.create(op.get_bind(), checkfirst=True)
    op.add_column('carts', sa.Column('category', cart_category, nullable=True))
    op.add_column('carts', sa.Column('weight_kg', sa.Numeric(precision=6, scale=1), nullable=True))
    op.add_column('carts', sa.Column('max_load_kg', sa.Numeric(precision=6, scale=1), nullable=True))
    op.add_column('carts', sa.Column('width_cm', sa.Numeric(precision=6, scale=1), nullable=True))
    op.add_column('carts', sa.Column('length_cm', sa.Numeric(precision=6, scale=1), nullable=True))
    op.add_column('carts', sa.Column('foldable', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('carts', sa.Column('weekly_rate', sa.Numeric(precision=10, scale=0), nullable=True))
    op.add_column('carts', sa.Column('per_rental_rate', sa.Numeric(precision=10, scale=0), nullable=True))
    op.alter_column('carts', 'daily_rate',
               existing_type=sa.NUMERIC(precision=10, scale=0),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carts', 'daily_rate',
               existing_type=sa.NUMERIC(precision=10, scale=0),
               nullable=False)
    op.drop_column('carts', 'per_rental_rate')
    op.drop_column('carts', 'weekly_rate')
    op.drop_column('carts', 'foldable')
    op.drop_column('carts', 'length_cm')
    op.drop_column('carts', 'width_cm')
    op.drop_column('carts', 'max_load_kg')
    op.drop_column('carts', 'weight_kg')
    op.drop_column('carts', 'category')
    sa.Enum(name='cart_category').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
