"""add cart lending_address

Revision ID: 97d7ad714e2a
Revises: 268848281cbf
Create Date: 2026-06-23 03:16:47.736177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97d7ad714e2a'
down_revision: Union[str, None] = '268848281cbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('lending_address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'lending_address')
    # ### end Alembic commands ###
